### ISSUE TITLE
change type specific getters to return AssociationProxy

### ISSUE THREAD

**Issue by elrayle** [samvera/hydra-works#100]
Modify type specific setters to return AssociationProxy which reponds to #=, #==, #<<, etc

Example change for Collection...

```
AssociationProxy.new(self, :collections)
```

Also remove the companion setter methods.

**Comment by elrayle** [comment]
This may be replaced by the move to services for CRUD.  See discussions at pcdm level before implementing here...  https://github.com/projecthydra-labs/hydra-pcdm/issues/89

**Comment by terrellt** [comment]
@elrayle Is this closed?

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/issues/89#issuecomment-123820302 seems to identify this as resolved by the introduction of `FilterAssociations`: https://github.com/samvera/active_fedora/blob/master/lib/active_fedora/associations/filter_association.rb
