### ISSUE TITLE
attached_files_of_type iterates unecessarily

### ISSUE THREAD

**Issue by jcoyne** [samvera/hydra-works#124]
attached_files_of_type loads all the metadata of all the files in the ldp:DirectContainer because it runs `reject` on the result set.  If we change the method to be `first_attached_file_of_type`, then it only needs to iterate until it finds the one it's looking for.

/cc @flyingzumwalt

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/pull/112/files#r31775050 addresses how this has been resolved with an effective solution
