### ISSUE TITLE
FitsDatastream does not exist in the Hydra::Works::CharacterizationService name context 

### ISSUE THREAD

**Issue by barmintor** [samvera/hydra-works#287]
The default value for opts[:parser_class] needs to be Hydra::Works::Characterization::FitsDatastream instead.

**Comment by barmintor** [comment]
This error occurs when Hydra::Works::Characterization has not been included in a model- it sets the parser_class default in a context where FitsDatastream resolves.

**Comment by awead** [comment]
@barmintor this should be fixed now. Can you confirm?
