### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hydra-works#343]

**Comment by jrgriffiniii** [comment]
@no-reply prefers that #346 be merged before the 1.0.0 release, but this will require a discussion (including the participation of @cjcolvar)

**Comment by tpendragon** [comment]
I'm of the opinion that hydra-works has had a stable-ish API for a long time and `1.0.0` is a formalization of that. I don't think #346 needs to be figured out first - once it is, it may or may not mean 2.0.0, which seems fine.
