### ISSUE TITLE
deprecated plugin/analysis class [solr.TrieIntField]

### ISSUE THREAD

**Issue by pscdodd** [samvera/hydra-works#355]
From the solr (Version 7.5.0) Log:
"Solr loaded a deprecated plugin/analysis class [solr.TrieIntField]. Please consult documentation how to replace it accordingly."

Trie fields are deprecated as of Solr 7.0. See http://lucene.apache.org/solr/7_1_0/solr-core/deprecated-list.html

Found in samvera 2.3.3

**Comment by pscdodd** [comment]
Other depreciated plugins:
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.TrieIntField]. Please consult documentation how to replace it accordingly.
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.TrieFloatField]. Please consult documentation how to replace it accordingly.
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.TrieLongField]. Please consult documentation how to replace it accordingly.
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.TrieDoubleField]. Please consult documentation how to replace it accordingly.
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.TrieDateField]. Please consult documentation how to replace it accordingly.
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.LatLonType]. Please consult documentation how to replace it accordingly.
31.10.2018, 13:54:06 | WARN false | x:hydra-development | SolrResourceLoader | Solr loaded a deprecated plugin/analysis class [solr.StandardFilterFactory]. Please consult documentation how to replace it accordingly.

**Comment by jcoyne** [comment]
This should be fixed by  #356

**Comment by jcoyne** [comment]
Also needs the upstream https://github.com/samvera/active_fedora/pull/1368
