### ISSUE TITLE
Solrize GenericWork

### ISSUE THREAD

**Issue by tpendragon** [samvera/hydra-works#63]
Initial guess would be that you'd want works to solrize their GenericFile's metadata? Do you reindex after a generic file is saved?

**Comment by jcoyne** [comment]
I'm not sure that a GenericWork should have GenericFile metadata except maybe for a list of ids of their GenericFiles.  I do think that GenericFiles should serialize the metadata of their attached Files though.  We want to be careful here. If we serialize too deeply, a simple save could cause hundreds of Fedora GET requests, making it slow.

**Comment by terrellt** [comment]
So it depends. If a GenericFile is descriptive metadata -about- the file on disk, and you don't solrize it to the work, and only Works are discoverable, then you'll never be able to find a Work based on its contained file names.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/active_fedora/pull/1223 pulled Solrizer into https://github.com/samvera/active_fedora (hence, I assume that this was addressed there).
