### ISSUE TITLE
Documentation: Add working example

### ISSUE THREAD

**Issue by elrayle** [samvera/hydra-works#83]
Develop and test a working example and update README.md.

**Comment by jcoyne** [comment]
@elrayle what is the status of this issue? Can we close it?

**Comment by grosscol** [comment]
https://github.com/elrayle/hydra-works-demo

Readme still needs updating.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-works/blob/master/README.md seems to thoroughly address basic usage within the code base, as well as outlining running tests within a local development environment.
