### ISSUE TITLE
Provide (optional) module for Default metadata

### ISSUE THREAD

**Issue by flyingzumwalt** [samvera/hydra-works#91]
Move Sufia::GenericFile::Metadata to Hydra::Works::File::DefaultMetadata

This should not be mixed into Works::FileBehaviors or Works::GenericFile.  It should just be available for people to mix basic DC metadata into their GenericFile implementations.

Note: This might belong in CurationConcerns instead of Works?

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/curation_concerns/issues/140#issuecomment-128039723 indicates that the decision was to leave this in place.
